CI: implement release pipeline (#371)

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -2,7 +2,16 @@
 # SPDX-License-Identifier: MIT
 
 name: Build
-on: [push, pull_request, workflow_dispatch]
+on:
+  push:
+  pull_request:
+  workflow_dispatch:
+    inputs:
+      create_release:
+        description: Create new release
+        type: boolean
+        required: false
+
 permissions: {}
 
 jobs:
@@ -56,3 +65,104 @@ jobs:
         uses: actions/attest@1e69f48acb82d1966a394da916b4c1698aa569d6 # v4.2.2
         with:
           subject-path: dist/
+
+  metadata:
+    needs: build
+    runs-on: ubuntu-slim
+    timeout-minutes: 15
+    outputs:
+      version: ${{ steps.version.outputs.version }}
+      notes: ${{ steps.notes.outputs.notes }}
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
+        with:
+          persist-credentials: false
+
+      - name: Store version
+        id: version
+        run: |
+          VERSION="$(python -m tinytag --version)"
+          echo "::notice::Version: $VERSION"
+          echo "version=$VERSION" >> "$GITHUB_OUTPUT"
+
+      - name: Store notes
+        id: notes
+        env:
+          VERSION: ${{ steps.version.outputs.version }}
+        run: |
+          NOTES="$(python data/scripts/extract_release_notes.py "$VERSION")"
+          echo "Release notes: $NOTES"
+          {
+            echo "notes<<EOF"
+            echo "$NOTES"
+            echo "EOF"
+          } >> "$GITHUB_OUTPUT"
+
+      - name: Validate version
+        if: inputs.create_release
+        env:
+          VERSION: ${{ steps.version.outputs.version }}
+        run: |
+          if [[ ! "$VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
+            echo "::error::Version is invalid. Expected format is X.Y.Z."
+            exit 1
+          fi
+
+      - name: Validate notes
+        if: inputs.create_release
+        env:
+          NOTES: ${{ steps.notes.outputs.notes }}
+        run: |
+          if [[ -z "$NOTES" ]]; then
+            echo "::error::Notes cannot be empty."
+            exit 1
+          fi
+
+  pypi-publish:
+    if: |
+      github.repository == 'tinytag/tinytag' &&
+      github.event_name == 'workflow_dispatch' && inputs.create_release
+    needs: [attestation, metadata]
+    runs-on: ubuntu-latest
+    timeout-minutes: 15
+    environment:
+      name: pypi
+      url: https://pypi.org/p/tinytag
+    permissions:
+      id-token: write
+    steps:
+      - name: Download artifacts
+        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
+        with:
+          name: dist
+          path: dist/
+
+      - name: Publish package to PyPI
+        uses: pypa/gh-action-pypi-publish@dc37677b2e1c63e2034f94d8a5b11f265b73ba33 # v1.14.2
+
+  github-release:
+    if: github.event_name == 'workflow_dispatch' && inputs.create_release
+    needs: [attestation, metadata]
+    runs-on: ubuntu-slim
+    timeout-minutes: 15
+    environment:
+      name: github-release
+    permissions:
+      contents: write
+    env:
+      GITHUB_TOKEN: ${{ github.token }}
+      VERSION: ${{ needs.metadata.outputs.version }}
+      NOTES: ${{ needs.metadata.outputs.notes }}
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
+        with:
+          persist-credentials: false
+
+      - name: Create release
+        run: |
+          gh release create "$VERSION" \
+            --title "$VERSION" \
+            --notes "$NOTES" \
+            --target "$GITHUB_SHA"
